# permissions for end users to edit templatedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: templatedsecret-editor-role
rules:
- apiGroups:
  - k8s.basilfx.net
  resources:
  - templatedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.basilfx.net
  resources:
  - templatedsecrets/status
  verbs:
  - get
