# permissions for end users to view templatedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: templatedsecret-viewer-role
rules:
- apiGroups:
  - k8s.basilfx.net
  resources:
  - templatedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.basilfx.net
  resources:
  - templatedsecrets/status
  verbs:
  - get
